apiVersion: v1
kind: ConfigMap
metadata:
  name: cinemaabyss-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # Database configuration
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}

  # Service URLs
  MONOLITH_URL: "http://{{ .Values.services.monolith.name }}:{{ .Values.services.monolith.service.port }}"
  MOVIES_SERVICE_URL: "http://{{ .Values.services.movies.name }}:{{ .Values.services.movies.service.port }}"
  EVENTS_SERVICE_URL: "http://{{ .Values.services.events.name }}:{{ .Values.services.events.service.port }}"
  PROXY_SERVICE_URL: "http://{{ .Values.services.proxy.name }}:{{ .Values.services.proxy.service.port }}"
  KAFKA_BROKER: {{ .Values.kafka.broker | quote }}
  MONOLITH_PORT: {{ .Values.services.monolith.env.PORT | quote }}
  PROXY_SERVICE_PORT: {{ .Values.services.proxy.env.PORT | quote }}
  MOVIES_SERVICE_PORT: {{ .Values.services.movies.env.PORT | quote }}
  EVENTS_SERVICE_PORT: {{ .Values.services.events.env.PORT | quote }}
  
  # Strangler Fig configuration
  GRADUAL_MIGRATION: {{ .Values.config.gradualMigration | quote }}
  MOVIES_MIGRATION_PERCENT: {{ .Values.config.moviesMigrationPercent | quote }}