apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ include "cinemaabyss.namespace" . }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.imagePullSecrets.registry }}": {
          "auth": "{{ printf "%s:%s" .Values.imagePullSecrets.username .Values.imagePullSecrets.password | b64enc }}"
        }
      }
    }