apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZV2R5WldkeWFWT21naGNGOXBkancxUnFVQnpValJhbmtBZmN6ZFFVMjB0VFdKSWNtQlhaVXBxWjFZeWNVTzFOWWY9In19fQ==
type: kubernetes.io/dockerconfigjson
